import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background px-6 py-12 font-body text-foreground">
      <div className="mx-auto max-w-2xl">
        <Link href="/home" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline">
          <ArrowLeft className="h-4 w-4" /> Back to App
        </Link>
        
        <h1 className="mb-2 font-headline text-4xl font-bold text-primary">Terms of Use</h1>
        <p className="mb-8 text-sm text-muted-foreground">Last Updated: December 5, 2025</p>

        <div className="space-y-6 text-sm leading-relaxed text-muted-foreground">
          <section>
            <h2 className="mb-3 font-headline text-xl font-bold text-foreground">1. Acceptance of Terms</h2>
            <p>
              By accessing or using <strong>The Quantum Cat</strong>, you agree to be bound by these Terms of Use. If you do not agree, please do not use the app.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-headline text-xl font-bold text-foreground">2. Entertainment Purpose Only</h2>
            <p className="font-semibold text-foreground">This app is for entertainment purposes only.</p>
            <p className="mt-2">
              The &ldquo;Quantum Messages&rdquo; and advice generated by the app are created by an Artificial Intelligence (AI). They are fictional, random, and often whimsical. <strong>Do not take them as professional, medical, legal, or life advice.</strong> We are not responsible for any decisions you make based on a digital cat.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-headline text-xl font-bold text-foreground">3. User Conduct</h2>
            <p>
              You agree not to misuse the app, attempt to reverse-engineer the code, or use the service for any illegal activities. We reserve the right to terminate accounts that violate these rules.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-headline text-xl font-bold text-foreground">4. Intellectual Property</h2>
            <p>
              The visual assets, code, and &ldquo;The Quantum Cat&rdquo; brand are owned by <strong>FlyBoat Creative</strong>. You may not copy or redistribute them without permission. You are, however, encouraged to share your generated cat results on social media!
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-headline text-xl font-bold text-foreground">5. AI Content Disclaimer</h2>
            <p>
              The text content in this app is generated dynamically by Google Gemini. While we tune the AI for safety, it may occasionally produce unpredictable results. We do not endorse every specific message generated by the model.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-headline text-xl font-bold text-foreground">6. Disclaimer of Warranties</h2>
            <p>
              The app is provided &ldquo;as is&rdquo; without warranties of any kind. We do not guarantee that the service will be uninterrupted or error-free.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-headline text-xl font-bold text-foreground">7. Contact</h2>
            <p>
              For support or inquiries, please contact: <br />
              <a href="mailto:adam@flyboat.online" className="font-bold text-primary hover:underline">adam@flyboat.online</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
